services:
  - type: web
    name: supportiq
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: supportiq
